# Generated by Django 5.2.17 on 2026-09-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
