# Generated by Django 5.2.17 on 2026-09-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_post_posteo'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
