# Generated by Django 5.2.17 on 2026-09-10 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_posteo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='posteo'),
        ),
    ]
